// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://airgbbeaaavckmbttaqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcmdiYmVhYWF2Y2ttYnR0YXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzk0MTMsImV4cCI6MjA2MzkxNTQxM30.XkA_dlzxb6phEp5iNy9EGBooo2LowTFgrGVKwY-hSPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);